FROM daocloud.io/library/centos

# download sourcecode
RUN yum -y install git java java-1.8.0-openjdk-devel.x86_64 maven
RUN cd /opt/ && git clone https://github.com/pzxwhc/Allen6314.git

EXPOSE 8080

# run
CMD touch /opt/flag.log && tail -f /opt/flag.log
